name: Tests

on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:

env:
  SYSTEM_PACKAGES: gcc g++ xvfb qtbase5-dev libegl1 libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 x11-utils libxcb-cursor0 libopengl0 libegl1-mesa

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    env:
      DISPLAY: ':99.0'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache APT Packages
      uses: awalsh128/cache-apt-pkgs-action@v1.4.1
      with:
        packages: ${{ env.SYSTEM_PACKAGES }}

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('.github/dependabot/constraints.txt') }}

    - name: Install Python dependencies
      run: |
        python3 -m pip install -e .[gui,backend,test] --constraint .github/dependabot/constraints.txt

    # cf. https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html
    - name: Setup xvfb
      run: |
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX

    - name: Test with pytest
      run: |
        python3 -m pytest --cov=damnit --cov-report=xml -v --xvfb-backend xvfb

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true

  publish:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: tests
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build packages
        run: |
          python3 -m pip install build
          python3 -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
